Traceback (most recent call last):
  File "/Users/bkim/mambaforge/envs/myenv_x86/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/bkim/mambaforge/envs/myenv_x86/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/bkim/mambaforge/envs/myenv_x86/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/bkim/mambaforge/envs/myenv_x86/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/bkim/mambaforge/envs/myenv_x86/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/bkim/mambaforge/envs/myenv_x86/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/bkim/mambaforge/envs/myenv_x86/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bkim/mambaforge/envs/myenv_x86/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
CREATE TABLE joinedtable2 AS 
SELECT a.w_geocode AS blockid, a.c000 AS total_jobs, b.cty AS county 
FROM ca_wac_2015 a
LEFT JOIN ca_xwalk b
ON a.w_geocode = b.tabblk2010
LIMIT 1000;
------------------


Error: table joinedtable2 already exists

